### ISSUE TITLE
stripeの商品追加, CSSの確認

### ISSUE THREAD

**Issue by Colorful12** [Colorful12/react_1#6]
# やって頂きたいこと
* [x]  cuisines配列で定義されるメニューを6つから7つに増やしました. 7つ目の商品「和風定食」の "url" と "price_id" が空なので追加をお願いしたいです.
* [x]   CSSでのサイズ指定時の単位を pix から rem または % に変更しました. mainブランチにmergeしてあるため、windowsでどのように表示されているか見ていただきたいです.

**Comment by Sugimotomatty** [comment]
cuisines配列の追加はやっておきました。サイズに関しては変わってないのかなと思います。ただ、そこは67%表示で対応できるかもです。

**Comment by Colorful12** [comment]
@Sugimotomatty 
ありがとうございます！
サイズ変わってないですか...、また考えます。
